---
- hosts: all
  become: yes
  tasks:
   - name: disable SELinux
     command: setenforce 0

   - name: disable SELinux on reboot
     selinux:
       state: disabled

   - name: Disabling Swap on all nodes
     shell: swapoff -a


   - name: Commenting Swap entries in /etc/fstab
     replace:
       path: /etc/fstab
       regexp: '(.*swap*)'
       replace: '#\1'
